parameters:
#    msi_cart.example.class: Msi\CartBundle\Example

services:
#    msi_cart.example:
#        class: %msi_cart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
